name: nightly-housekeeper
on:
    schedule:
        - cron: '0 2 * * *'
    workflow_dispatch:
jobs:
    clean-up:
        runs-on: ubuntu-latest
        steps:
            - run: date
            - run: echo "Running nightly cleanup"
            - run: echo "Housekeeping complete"