name: Ordered Pipeline
on:
    push:
    workflow_dispatch:
jobs:
    setup:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: exit 1
            - run: echo "Setup done"
    verify:
        runs-on: ubuntu-latest
        needs: 
            setup
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: python --version
            - run: echo "Verify done"
        
    finish:
        runs-on: ubuntu-latest
        needs: 
            verify
        steps:
            - run: echo "Pipeline finished"