name: PR-gatekeeper
on:
    #pull_request:
    #    branches:
    #        - main
    workflow_dispatch:

jobs:

    check:
        runs-on: ubuntu-latest
        steps:
            - name: The PR branch merged into
              run: echo "PR is merged into ${{github.base_ref}}"
            - name: Prints PR number
              run: echo "PR number is ${{github.event.number}}"
            - name: Finish
              run: echo "Gatekeeper checks complete"