name: Subfolder Builder
on:
    #push:
    workflow_dispatch:

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: app
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-python@v5
              with:
                python-version: '3.11'
            - run: pwd
            - run: ls
            - run: echo "Build folder confirmed"

